[package]
name = "fluid-rust"
version = "0.1.0"
authors = ["Pepijn Dragt <pepijn.dragt@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
hashbrown = "0.1.8"
wasm-bindgen = "0.2.33"

[lib]
crate-type = ["cdylib"]
